### ISSUE TITLE
Database Setup

### ISSUE THREAD

**Issue by DieDyeDai** [cssgunc/breast-cancer-hub#2]
Sync user settings and authentication (email, password hash) to a database
- [x] Set up database server https://github.com/cssgunc/breast-cancer-hub/issues/6
- [x] Set up APIs to access and update database https://github.com/cssgunc/breast-cancer-hub/issues/7
- [x] Set up authentication API  https://github.com/cssgunc/breast-cancer-hub/issues/8
